[versions]
kotlin = "1.6.10"
kotlinCoroutines = "1.6.3"
hilt = "2.42"
navigation = "2.4.2"
compose = "1.1.1"
lifecycle = "2.5.0"
junit = "4.13.2"

[libraries]
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
jackson = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.2"

timber = "com.jakewharton.timber:timber:5.0.1"

junit = { module = "junit:junit", version.ref = "junit" }
mockk = "io.mockk:mockk:1.12.4"

[bundles]
compose = [
    "compose-ui",
    "compose-tooling",
    "compose-foundation",
    "compose-material",
    "compose-material-icons"
]
