[versions]
kotlin = "1.6.10"
kotlinCoroutines = "1.6.3"
hilt = "2.38.1"
navigation = "2.4.2"
junit = "4.13.2"

[libraries]
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

junit = { module = "junit:junit", version.ref = "junit" }

[bundles]
